### ISSUE TITLE
API availability

### ISSUE THREAD

**Issue by MtnBiker** [GaborFarkas/mastering_openlayers3#14]
p9 of the printed book states that API is available for v3.11.0. As far as I can tell the closest version of the API available is v.3.20.1. https://openlayers.org/en/v3.20.1/apidoc/. I'm just starting the book so can't guess what the impact will be. This is probably Errata.

**Comment by GaborFarkas** [comment]
Well yes, I can see, the API docs for older versions have gone missing. Fortunately, you can build your own local API documentation for any given version. You just have to read into Chapter 10 first and follow the instructions to set up your Node.js environment (pp. 259-262) and build the API docs with JSDoc (p. 274).

**Comment by MtnBiker** [comment]
Good do know. I skimmed the [changelog](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#v3200) for OL and doubt using  v.3.20.1 API docs will be much of a an issue. In fact, I think it might be a benefit, it will remind us, the students, that some things have changed in the later versions we're likely to be using. (Maybe the current state of the world helps one to look for the positive). 

PS So far I'm finding the book to be very good. Thorough without being tedious. I'd better say this now because I don't doubt it will get more difficult as I'm not a lover of JavaScript. But I'll look at building the docs as an exercise once I work through Chap 10.

**Comment by GaborFarkas** [comment]
It's really nice to see your enthusiasm. These are the times when I think it was really worth writing this book. Good luck with learning OL and web mapping! Hope you'll have some fun doing so, too.
