### ISSUE TITLE
categorized colors are invalid (sometimes)

### ISSUE THREAD

**Issue by WillieMaddox** [GaborFarkas/mastering_openlayers3#3]
When clicking on the categorized button repeatedly, I notice that on occasion the colors for a particular property are incorrect.  For example, when looking at the continents property of the world_countries.geojson, sometimes the colors of the countries are different.  This happens quite infrequently and the continent that it happens on seems completely random.  The issue is in the randomHexColor method.  If a small number is generated, the leading zeros get lobbed off and you end up with a hex string that is less than 6 chars.  The following method is pseudorandom, but it guarantees a 6 digit hex and is superfast.

``` javascript
layerTree.prototype.randomHexColor = function() {
    return '#' + Math.random().toString(16).slice(2,6);
};
```

Just thought I'd share.

**Comment by GaborFarkas** [comment]
Nice finding! Your solution should be used in production code, as it is more lightweight, however for educational purposes, I find the proper random number generator/clamper more appropriate. I will create a commit with the fixed function this evening.

There is one typo in your proposed function, though. It should be:

``` javascript
layerTree.prototype.randomHexColor = function() {
    return '#' + Math.random().toString(16).slice(2,8);
};
```
