### ISSUE TITLE
ch05_draw handleEvents question

### ISSUE THREAD

**Issue by WillieMaddox** [GaborFarkas/mastering_openlayers3#4]
It seems to me like the logic in `selectEventEmitter` actually prevents the `var error` in `handleEvents` from evaluating to anything other than false.

For example, 

``` javascript
error = (layerType !== type && layerType !== 'geomcollection') ? true : false;
```

should never be true. The emitter control guarantees it.  Also,

``` javascript
var selectedLayer = this.layertree.getLayerById(this.layertree.selectedLayer.id);
error = selectedLayer instanceof ol.layer.Vector ? '' : 'Please select a valid vector layer.';
```

In what situations might I encounter a vector layer that would be considered invalid?
From what I can tell, the only way you can fire `drawend` is to call `handleEvents`.  The only way to call `handleEvents` is to select a draw control. And the only way to select a draw control is if a vector layer that supports that draw control is selected _a priori_.  According to the book, Page 119,

> If the layer has a vector type, we use a permissive logic. We enable every editing control, check for the type of the layer, and disable the inappropriate drawing controls. We also deactivate them; therefore, they do not get stuck if we change the selected layer during an editing session. If the layer is **not a vector**, we use a restrictive logic and **disable every editing control**.

And according to Page 120, paragraph 1,

> If we are working with a draw line or draw polygon tool, we **check for the active layer**. **If it is not a vector**, we simply call the interaction's `finishDrawing` method.

So, checking to see if the active layer is indeed a vector seems unnecessary?

The book does however say,

> On the other hand, the disabled property of a DOM element can be overridden from the browser; thus, we should make the drawing process completely foolproof.

Maybe this is why all the error checking is needed?  If so, how exactly could I go about "overriding a DOM element from the browser" to force the error?

**Comment by GaborFarkas** [comment]
These are extra layers of security. I like to make my code as foolproof as possible. If the code depends on a status, which can be modified outside of the code (like the DOM `disabled` property), it is vulnerable. 

You can override that property from your Developer Tools. In the Elements tab select a disabled `button` element, and simply remove the `disabled` tab. You will see, the control is enabled. However, if you click on it, the application will return an error.

**Comment by WillieMaddox** [comment]
Thank you for clarifying this.
