### ISSUE TITLE
styleGraduated missing typeof

### ISSUE THREAD

**Issue by WillieMaddox** [GaborFarkas/mastering_openlayers3#9]
``` javascript
layerTree.prototype.styleGraduated = function (layer, attribute) {
    if (layer.get('headers')[attribute] === 'string') {
        ...
    }
};
```

should be,

``` javascript
layerTree.prototype.styleGraduated = function (layer, attribute) {
    if (typeof layer.get('headers')[attribute] === 'string') {
        ...
    }
};
```

**Comment by GaborFarkas** [comment]
There is no need for `typeof`. The header object stores properties as names, and types as values. I used two types in the example: `string` and `integer`.

**Comment by WillieMaddox** [comment]
That's weird.  Because when I look at the output of:

```javascript
layer.get('headers')[attribute]
```
I get, for example, something like.

`'asia'` if `attribute = 'continent'`

and `'asia' === 'string'` returns `false`
